const REVIEWED_ON = '2026-08-22';

export interface GroceryPick {
  readonly label: string;
  readonly searchQuery: string;
  readonly reason: string;
}

export interface GroceryGuide {
  readonly id: string;
  readonly name: string;
  readonly aliases: readonly string[];
  readonly explanation: string;
  readonly typicalSection: string;
  readonly packageGuidance: string;
  readonly budget: GroceryPick;
  readonly bestForDish: GroceryPick;
  readonly storage: string;
  readonly dietaryCheck: string;
  readonly reviewedOn: string;
}

export interface RetailerLinks {
  readonly heb: string;
  readonly instacart: string;
  readonly walmart: string;
}

type GroceryGuideInput = Omit<GroceryGuide, 'aliases' | 'reviewedOn'> & {
  readonly aliases?: readonly string[];
};

function guide(input: GroceryGuideInput): GroceryGuide {
  return Object.freeze({
    ...input,
    aliases: Object.freeze([...(input.aliases ?? [])]),
    budget: Object.freeze({ ...input.budget }),
    bestForDish: Object.freeze({ ...input.bestForDish }),
    reviewedOn: REVIEWED_ON,
  });
}

export const GROCERY_GUIDES: readonly GroceryGuide[] = Object.freeze([
  guide({
    id: 'starter:tofu-firm',
    name: 'Extra-firm tofu',
    explanation: 'A dense soybean curd that keeps its shape when seared, baked, or stirred into a sauce.',
    typicalSection: 'Refrigerated tofu and meat alternatives',
    packageGuidance: 'Buy one 14–16 oz block for a substantial single-serving meal.',
    budget: { label: 'Store-brand extra-firm tofu', searchQuery: 'extra firm tofu 14 oz', reason: 'The standard water-packed block works for most bowls, curries, and stir-fries.' },
    bestForDish: { label: 'Super-firm high-protein tofu', searchQuery: 'super firm high protein tofu 16 oz', reason: 'It needs less pressing and develops a firmer browned edge.' },
    storage: 'Keep refrigerated; refrigerate an opened block in fresh water and use promptly.',
    dietaryCheck: 'Choose a plainly labeled vegan tofu and review flavored versions for animal-derived sauces.',
  }),
  guide({
    id: 'starter:paneer',
    name: 'Paneer',
    explanation: 'A mild Indian fresh cheese that softens while cooking but does not melt into the sauce.',
    typicalSection: 'Specialty cheese or deli case',
    packageGuidance: 'A 10–14 oz block is practical for one very hearty meal or two moderate portions.',
    budget: { label: 'Standard paneer block', searchQuery: 'paneer cheese block 12 oz', reason: 'A plain block can be cubed for curries, bowls, and wraps without extra preparation.' },
    bestForDish: { label: 'Fresh low-sodium paneer', searchQuery: 'fresh low sodium paneer', reason: 'A fresh block stays tender and lets the cook control the seasoning.' },
    storage: 'Keep refrigerated and use within the package guidance after opening.',
    dietaryCheck: 'Check that the cheese uses microbial or vegetarian enzymes when avoiding animal rennet.',
  }),
  guide({
    id: 'starter:tempeh',
    name: 'Tempeh',
    explanation: 'A firm fermented soybean cake with a nutty flavor and a chewy, sliceable texture.',
    typicalSection: 'Refrigerated tofu and meat alternatives',
    packageGuidance: 'One 8 oz package supplies a generous protein portion for one meal.',
    budget: { label: 'Plain original tempeh', searchQuery: 'plain original tempeh 8 oz', reason: 'The unseasoned format is flexible and avoids paying for a prepared sauce.' },
    bestForDish: { label: 'Organic plain soy tempeh', searchQuery: 'organic plain soy tempeh 8 oz', reason: 'A simple ingredient list takes marinades and spice pastes predictably.' },
    storage: 'Keep refrigerated; freeze unopened extra packages for longer storage.',
    dietaryCheck: 'Plain tempeh is vegetarian; review marinated varieties for fish sauce or animal stock.',
  }),
  guide({
    id: 'starter:seitan',
    name: 'Seitan',
    explanation: 'A chewy cooked wheat-protein food used in stir-fries, wraps, and saucy skillets.',
    typicalSection: 'Refrigerated meat alternatives',
    packageGuidance: 'Plan on one 8 oz package for a protein-heavy single-serving meal.',
    budget: { label: 'Plain seitan strips', searchQuery: 'plain seitan strips 8 oz', reason: 'Plain strips work across cuisines and can be seasoned at home.' },
    bestForDish: { label: 'Lower-sodium plain seitan', searchQuery: 'low sodium plain seitan', reason: 'It leaves more room for soy sauce, salsa, or curry seasoning.' },
    storage: 'Keep refrigerated and use an opened package promptly; freeze if the label permits.',
    dietaryCheck: 'Verify a vegan label and avoid varieties made with meat broth; contains wheat.',
  }),
  guide({
    id: 'starter:eggs',
    name: 'Large eggs',
    explanation: 'Whole eggs add complete protein, richness, and structure to rice, noodle, and tortilla meals.',
    typicalSection: 'Dairy and eggs',
    packageGuidance: 'A 12-count carton covers several recipes; use large eggs so recipe quantities stay consistent.',
    budget: { label: 'Store-brand large eggs', searchQuery: 'large eggs 12 count', reason: 'Large eggs match the recipe measurements without a specialty format.' },
    bestForDish: { label: 'Large pasture-raised eggs', searchQuery: 'pasture raised large eggs 12 count', reason: 'Choose these when yolk flavor is prominent in the finished dish.' },
    storage: 'Keep refrigerated in the carton and follow the package date.',
    dietaryCheck: 'Eggs fit the ovo-lacto catalog; egg substitutes need a separate ingredient review.',
  }),
  guide({
    id: 'starter:greek-yogurt',
    name: 'Plain Greek yogurt',
    explanation: 'A strained yogurt that adds protein and creamy body to sauces, marinades, and bowls.',
    typicalSection: 'Yogurt case',
    packageGuidance: 'A 32 oz tub is useful across several meals and produces less packaging than single cups.',
    budget: { label: 'Store-brand plain whole-milk Greek yogurt', searchQuery: 'plain whole milk Greek yogurt 32 oz', reason: 'A large plain tub works as both an ingredient and a topping.' },
    bestForDish: { label: 'Plain 5% Greek yogurt', searchQuery: 'plain 5 percent Greek yogurt 32 oz', reason: 'The fuller texture resists splitting and makes a richer sauce.' },
    storage: 'Keep refrigerated, use a clean spoon, and close the tub tightly.',
    dietaryCheck: 'Choose plain yogurt and check flavored products for gelatin.',
  }),
  guide({
    id: 'starter:cottage-cheese',
    name: 'Cottage cheese',
    explanation: 'A mild fresh curd cheese that blends into creamy sauces or adds protein to a bowl.',
    typicalSection: 'Cultured dairy case',
    packageGuidance: 'A 24 oz tub supports two or three hearty recipes.',
    budget: { label: 'Store-brand cottage cheese', searchQuery: 'cottage cheese 24 oz', reason: 'The standard tub is versatile for blending, spooning, or stuffing.' },
    bestForDish: { label: '4% small-curd cottage cheese', searchQuery: '4 percent small curd cottage cheese 24 oz', reason: 'It blends smoothly and stays creamy when warmed gently.' },
    storage: 'Keep refrigerated and use a clean utensil to protect the opened tub.',
    dietaryCheck: 'Check for vegetarian or microbial enzymes when avoiding animal-derived rennet.',
  }),
  guide({
    id: 'starter:cheddar',
    name: 'Cheddar or Monterey Jack',
    explanation: 'A firm melting cheese used to bind quesadillas, finish bowls, and enrich sauces.',
    typicalSection: 'Packaged cheese',
    packageGuidance: 'An 8–16 oz block is easy to grate and keeps better than an opened bag of shreds.',
    budget: { label: 'Store-brand cheese block', searchQuery: 'cheddar cheese block 16 oz', reason: 'A block usually handles both shredding and slicing without anti-caking powder.' },
    bestForDish: { label: 'Sharp cheddar or Monterey Jack block', searchQuery: 'sharp cheddar Monterey Jack block', reason: 'Sharp cheddar brings more flavor, while Jack gives a particularly smooth melt.' },
    storage: 'Wrap the opened block closely and refrigerate.',
    dietaryCheck: 'Look for microbial or vegetarian enzymes when avoiding animal rennet.',
  }),
  guide({
    id: 'starter:mozzarella',
    name: 'Mozzarella',
    explanation: 'A mild cheese prized for an even melt in pasta bakes, flatbreads, and stuffed wraps.',
    typicalSection: 'Packaged cheese',
    packageGuidance: 'Buy an 8–16 oz block; low-moisture mozzarella is the most useful cooked-meal format.',
    budget: { label: 'Low-moisture mozzarella block', searchQuery: 'low moisture mozzarella block 16 oz', reason: 'It grates cleanly and melts without releasing as much water.' },
    bestForDish: { label: 'Whole-milk low-moisture mozzarella', searchQuery: 'whole milk low moisture mozzarella block', reason: 'It gives cooked dishes a richer, more elastic melt.' },
    storage: 'Refrigerate the block tightly wrapped after opening.',
    dietaryCheck: 'Check for microbial or vegetarian enzymes when avoiding animal rennet.',
  }),
  guide({
    id: 'starter:edamame',
    name: 'Shelled edamame',
    explanation: 'Tender young soybeans that add protein and color without thawing a whole pod.',
    typicalSection: 'Frozen vegetables',
    packageGuidance: 'A 10–12 oz bag supplies one large bowl or several smaller additions.',
    budget: { label: 'Store-brand shelled edamame', searchQuery: 'frozen shelled edamame 12 oz', reason: 'Shelled beans avoid paying for and discarding pods.' },
    bestForDish: { label: 'Plain steam-in-bag shelled edamame', searchQuery: 'plain steam in bag shelled edamame', reason: 'It is quick to portion and has no sauce competing with the recipe.' },
    storage: 'Keep frozen and return the closed bag to the freezer promptly.',
    dietaryCheck: 'Choose a plain product without nonvegetarian seasoning; contains soy.',
  }),
  guide({
    id: 'starter:chickpeas',
    name: 'Chickpeas',
    explanation: 'Firm, nutty legumes also called garbanzo beans or chana.',
    typicalSection: 'Canned and dried beans',
    packageGuidance: 'Recipe quantities are cooked and drained; two 15 oz cans cover a very hearty portion, while a 1 lb dry bag is the batch-cooking option.',
    budget: { label: 'Dry chickpeas', searchQuery: 'dry chickpeas 1 lb', reason: 'A dry bag produces several cooked portions when time allows for soaking.' },
    bestForDish: { label: 'No-salt-added canned chickpeas', searchQuery: 'no salt added chickpeas 15 oz', reason: 'Canned beans make a fast meal and let the recipe control its salt.' },
    storage: 'Keep dry beans sealed; refrigerate drained cooked beans and use promptly.',
    dietaryCheck: 'Plain chickpeas are vegetarian; review seasoned cans for broth.',
  }),
  guide({
    id: 'starter:black-beans',
    name: 'Black beans',
    explanation: 'Creamy dark legumes suited to burritos, rice bowls, soups, and quesadillas.',
    typicalSection: 'Canned and dried beans',
    packageGuidance: 'Recipe quantities are cooked and drained; two 15 oz cans cover a large bean portion, while a 1 lb dry bag is suited to batch cooking.',
    budget: { label: 'Dry black beans', searchQuery: 'dry black beans 1 lb', reason: 'Cooking from dry gives several portions and control over seasoning.' },
    bestForDish: { label: 'No-salt-added canned black beans', searchQuery: 'no salt added black beans 15 oz', reason: 'They can be rinsed and used immediately without bringing excess salt.' },
    storage: 'Store dry beans airtight; refrigerate opened canned beans in a separate container.',
    dietaryCheck: 'Choose plain beans and avoid products seasoned with animal stock.',
  }),
  guide({
    id: 'starter:kidney-beans',
    name: 'Kidney beans',
    explanation: 'Large red beans known as rajma when cooked in a spiced tomato gravy.',
    typicalSection: 'Canned and dried beans',
    packageGuidance: 'Recipe quantities are cooked and drained; buy two 15 oz cans for a large quick-recipe portion. Dry beans require a separate long preparation before recipe timing begins.',
    budget: { label: 'Plain canned kidney beans', searchQuery: 'canned red kidney beans 15 oz', reason: 'Fully cooked canned beans are the dependable default for the short recipe times in this collection.' },
    bestForDish: { label: 'No-salt-added canned kidney beans', searchQuery: 'no salt added canned kidney beans 15 oz', reason: 'They are fully cooked for quick use and leave seasoning under the cook’s control.' },
    storage: 'If using dry kidney beans, soak at least 5 hours, discard the soaking water, briskly boil in fresh water for at least 10 minutes, then cook fully until tender. Refrigerate cooked beans promptly.',
    dietaryCheck: 'Plain kidney beans are vegetarian; avoid cans made with meat seasoning.',
  }),
  guide({
    id: 'starter:pinto-beans',
    name: 'Pinto or vegetarian refried beans',
    explanation: 'Creamy speckled beans used whole or mashed for tacos, wraps, and rice bowls.',
    typicalSection: 'Canned and dried beans',
    packageGuidance: 'Recipe quantities are cooked or prepared; buy one or two 15–16 oz cans as the recipe amount requires, or use a 1 lb dry bag for batch cooking.',
    budget: { label: 'Dry pinto beans', searchQuery: 'dry pinto beans 1 lb', reason: 'A dry bag makes several portions of whole or mashed beans.' },
    bestForDish: { label: 'Vegetarian fat-free refried beans', searchQuery: 'vegetarian fat free refried beans 16 oz', reason: 'The prepared texture makes a fast, even layer in wraps and quesadillas.' },
    storage: 'Store dry beans sealed; refrigerate opened prepared beans in a separate container.',
    dietaryCheck: 'Refried beans must say vegetarian or explicitly contain no lard or meat stock.',
  }),
  guide({
    id: 'starter:lentils',
    name: 'Brown or green lentils',
    explanation: 'Small legumes that become tender while keeping enough shape for bowls and stews.',
    typicalSection: 'Dried beans and grains',
    packageGuidance: 'Recipe quantities are cooked; a 1 lb dry bag makes several meal-size portions after simmering according to the package.',
    budget: { label: 'Brown lentils', searchQuery: 'dry brown lentils 1 lb', reason: 'Brown lentils are widely useful and cook without soaking.' },
    bestForDish: { label: 'Green lentils', searchQuery: 'dry green lentils 1 lb', reason: 'Green lentils stay firmer in meal-prep bowls and saucy skillets.' },
    storage: 'Keep dry in an airtight container; refrigerate cooked lentils for short-term use.',
    dietaryCheck: 'Plain dry lentils are vegetarian; inspect prepared pouches for animal broth.',
  }),
  guide({
    id: 'starter:red-lentils',
    name: 'Red lentils',
    explanation: 'Hulled split lentils, also called masoor dal, that cook quickly into a creamy base.',
    typicalSection: 'Dried beans or international foods',
    packageGuidance: 'Recipe quantities are cooked; a 1–2 lb dry bag yields several curries or soups after simmering according to the package.',
    budget: { label: 'Dry red lentils', searchQuery: 'dry red lentils 1 lb', reason: 'They need no soaking and thicken a meal with little preparation.' },
    bestForDish: { label: 'Hulled split masoor dal', searchQuery: 'hulled split masoor dal', reason: 'Evenly split lentils soften at the same rate for a smooth dal.' },
    storage: 'Keep sealed in a cool, dry place.',
    dietaryCheck: 'Plain red lentils are vegetarian; avoid pre-seasoned mixes with animal stock.',
  }),
  guide({
    id: 'starter:chana-dal',
    name: 'Chana dal',
    explanation: 'Split, hulled chickpeas with a firm, nutty bite after cooking.',
    typicalSection: 'Indian or international dry goods',
    packageGuidance: 'Recipe quantities are cooked; a 1–2 lb dry bag covers several portions after the dal is simmered until tender.',
    budget: { label: 'Dry chana dal', searchQuery: 'chana dal 1 lb', reason: 'The plain dry pulse stores well and can be seasoned for many dishes.' },
    bestForDish: { label: 'Evenly split fresh-stock chana dal', searchQuery: 'split chickpeas chana dal', reason: 'Uniform pieces cook more evenly and keep the intended tender bite.' },
    storage: 'Keep airtight in a cool, dry pantry.',
    dietaryCheck: 'Plain chana dal is vegetarian; review instant dal packets for ghee and broth ingredients.',
  }),
  guide({
    id: 'starter:urad-dal',
    name: 'Whole black urad dal',
    explanation: 'Small black gram used to give dal makhani and slow-simmered stews a creamy body.',
    typicalSection: 'Indian or international dry goods',
    packageGuidance: 'Recipe quantities are cooked; a 1–2 lb dry bag is sufficient for several portions after soaking and fully simmering the dal.',
    budget: { label: 'Dry whole black gram', searchQuery: 'whole black gram urad 1 lb', reason: 'The plain whole pulse is the flexible pantry format.' },
    bestForDish: { label: 'Whole black urad dal', searchQuery: 'whole black urad dal', reason: 'Whole urad gives dal makhani its characteristic dark skins and creamy interior.' },
    storage: 'Keep sealed in a cool, dry place.',
    dietaryCheck: 'Plain urad is vegetarian; inspect prepared pouches for animal-derived flavoring.',
  }),
  guide({
    id: 'starter:basmati-rice',
    name: 'Basmati rice',
    explanation: 'An aromatic long-grain rice that cooks into separate, fluffy grains.',
    typicalSection: 'Rice or international foods',
    packageGuidance: 'Recipe quantities are cooked; buy dry rice and prepare the package-directed amount needed to reach the listed cooked portion. A 2–5 lb bag supports regular use.',
    budget: { label: 'Store-brand basmati rice', searchQuery: 'basmati rice 5 lb', reason: 'A plain multipound bag is useful across curries, bowls, and biryani-style meals.' },
    bestForDish: { label: 'Aged basmati rice', searchQuery: 'aged basmati rice 5 lb', reason: 'Aged grains tend to cook longer and more separate for pilafs and biryani.' },
    storage: 'Keep dry rice airtight away from heat and moisture.',
    dietaryCheck: 'Plain rice is vegetarian; review flavored packets for animal stock.',
  }),
  guide({
    id: 'starter:brown-rice',
    name: 'Brown rice',
    explanation: 'Whole-grain rice with a chewy texture and intact bran layer.',
    typicalSection: 'Rice and grains',
    packageGuidance: 'Recipe quantities are cooked; buy dry rice and prepare the package-directed amount needed to reach the listed cooked portion. A 2–5 lb bag supports several meals.',
    budget: { label: 'Store-brand long-grain brown rice', searchQuery: 'long grain brown rice 2 lb', reason: 'It is a versatile base for bowls, stir-fries, and casseroles.' },
    bestForDish: { label: 'Parboiled brown rice', searchQuery: 'parboiled brown rice', reason: 'It holds its texture well in meal-prep dishes and reheats cleanly.' },
    storage: 'Keep airtight; the bran oils make brown rice best used sooner than white rice.',
    dietaryCheck: 'Choose plain rice rather than broth-seasoned packets.',
  }),
  guide({
    id: 'starter:quinoa',
    name: 'Quinoa',
    explanation: 'A small seed cooked like a grain, with a light texture and useful protein.',
    typicalSection: 'Rice and specialty grains',
    packageGuidance: 'Recipe quantities are cooked; a 12–16 oz dry bag makes several cooked portions when prepared according to its package.',
    budget: { label: 'Store-brand white quinoa', searchQuery: 'white quinoa 16 oz', reason: 'White quinoa is mild, quick-cooking, and broadly useful.' },
    bestForDish: { label: 'Pre-rinsed tri-color quinoa', searchQuery: 'pre rinsed tri color quinoa', reason: 'The mixed colors hold a little more visible texture in composed bowls.' },
    storage: 'Keep dry and airtight; refrigerate cooked quinoa promptly.',
    dietaryCheck: 'Plain quinoa is vegetarian; inspect seasoned blends for stock.',
  }),
  guide({
    id: 'starter:pasta',
    name: 'Dry pasta',
    explanation: 'Durum-wheat noodles that provide a sturdy, calorie-dense base for sauces and bakes.',
    typicalSection: 'Pasta and pasta sauce',
    packageGuidance: 'Recipe quantities labeled cooked are measured after boiling and draining; buy one 16 oz dry box, then prepare only the amount needed for the listed cooked portion.',
    budget: { label: 'Store-brand durum pasta', searchQuery: 'dry pasta 16 oz', reason: 'A standard shape offers the broadest use at home.' },
    bestForDish: { label: 'Bronze-cut pasta', searchQuery: 'bronze cut pasta 16 oz', reason: 'Its rougher surface grips thick tomato and cheese sauces.' },
    storage: 'Keep dry pasta sealed in a cool pantry.',
    dietaryCheck: 'Most dry pasta is vegetarian, but review filled or flavored pasta for meat ingredients.',
  }),
  guide({
    id: 'starter:chickpea-pasta',
    name: 'Chickpea pasta',
    explanation: 'Pasta made primarily from chickpeas, with more protein and fiber than standard noodles.',
    typicalSection: 'Pasta or natural foods',
    packageGuidance: 'An 8–12 oz box is a generous base for one protein-heavy meal.',
    budget: { label: 'Store-brand chickpea pasta', searchQuery: 'chickpea pasta 8 oz', reason: 'The basic legume pasta supplies the intended macros without added flavors.' },
    bestForDish: { label: 'Single-ingredient chickpea pasta', searchQuery: 'single ingredient chickpea pasta', reason: 'A simple formula gives predictable cooking and nutrition.' },
    storage: 'Keep the dry box sealed; refrigerate cooked leftovers.',
    dietaryCheck: 'Check that chickpeas are the main ingredient and that no egg restriction applies to the eater.',
  }),
  guide({
    id: 'starter:whole-wheat-tortilla',
    name: 'Large whole-wheat wraps',
    explanation: 'Flexible wheat flatbreads sized to hold a full meal without tearing.',
    typicalSection: 'Tortillas and flatbreads',
    packageGuidance: 'Buy an 8–10 count burrito-size package and freeze extras with separators.',
    budget: { label: 'Store-brand whole-wheat wraps', searchQuery: 'whole wheat burrito tortillas 8 count', reason: 'A large basic wrap carries a substantial filling in one piece.' },
    bestForDish: { label: 'High-fiber burrito-size wraps', searchQuery: 'high fiber burrito size wraps', reason: 'The larger, sturdier format handles moist beans and vegetables better.' },
    storage: 'Seal tightly; refrigerate or freeze according to the label.',
    dietaryCheck: 'Read the ingredient list to exclude lard or animal-derived shortening.',
  }),
  guide({
    id: 'starter:fajita-tortillas',
    name: 'Fajita flour tortillas',
    explanation: 'Small soft wheat tortillas suited to tacos, folded quesadillas, and layered skillet meals.',
    typicalSection: 'Tortillas or store bakery',
    packageGuidance: 'A 20-count package supports several meals; use multiple tortillas for a substantial serving.',
    budget: { label: 'Packaged store-brand fajita tortillas', searchQuery: 'fajita flour tortillas 20 count', reason: 'The packaged format stores well and is easy to portion.' },
    bestForDish: { label: 'Fresh bakery flour tortillas', searchQuery: 'fresh bakery flour tortillas 20 count', reason: 'Fresh tortillas are especially soft and flavorful in simple tacos.' },
    storage: 'Seal tightly and freeze extra tortillas if they will not be used soon.',
    dietaryCheck: 'Check the label for lard and choose tortillas made with vegetable fat.',
  }),
  guide({
    id: 'starter:corn-tortillas',
    name: 'Corn tortillas',
    explanation: 'Thin nixtamalized-corn flatbreads used for tacos, enchiladas, and crisp tostada-style meals.',
    typicalSection: 'Tortillas and flatbreads',
    packageGuidance: 'A 20–30 count package is normal; use several tortillas for one large meal.',
    budget: { label: 'Store-brand white corn tortillas', searchQuery: 'white corn tortillas 30 count', reason: 'The simple packaged format is flexible and freezes well.' },
    bestForDish: { label: 'Fresh local corn tortillas', searchQuery: 'fresh corn tortillas', reason: 'A fresher tortilla bends and toasts with less cracking.' },
    storage: 'Refrigerate after opening and freeze extra stacks with a separator.',
    dietaryCheck: 'Plain corn tortillas are typically vegetarian; verify flavored varieties and shared-facility needs.',
  }),
  guide({
    id: 'starter:naan',
    name: 'Naan',
    explanation: 'A soft leavened Indian flatbread used to scoop curries or build flatbread meals.',
    typicalSection: 'Bakery, international foods, or freezer',
    packageGuidance: 'A 4–6 count package gives enough bread for one or two substantial meals.',
    budget: { label: 'Packaged plain naan', searchQuery: 'plain naan 4 count', reason: 'Plain naan works with any curry and reheats quickly.' },
    bestForDish: { label: 'Refrigerated or frozen tandoori-style naan', searchQuery: 'tandoori style plain naan', reason: 'It tends to char and puff more convincingly when reheated.' },
    storage: 'Refrigerate after opening or freeze with sheets between pieces.',
    dietaryCheck: 'Review the label for lard or animal-derived enzymes; dairy and egg are allowed here.',
  }),
  guide({
    id: 'starter:paratha',
    name: 'Frozen paratha',
    explanation: 'A layered Indian flatbread cooked from frozen until crisp outside and tender within.',
    typicalSection: 'International freezer',
    packageGuidance: 'A 5–20 count package stores well; plan on more than one for a large meal.',
    budget: { label: 'Plain frozen paratha multipack', searchQuery: 'plain frozen paratha multipack', reason: 'The plain multipack can accompany many different fillings and curries.' },
    bestForDish: { label: 'Whole-wheat plain paratha', searchQuery: 'whole wheat frozen paratha', reason: 'It brings a heartier flavor while retaining the layered format.' },
    storage: 'Keep frozen and remove only the pieces needed for cooking.',
    dietaryCheck: 'Check the fat source and exclude lard; inspect stuffed versions for meat.',
  }),
  guide({
    id: 'starter:pita',
    name: 'Pita bread',
    explanation: 'A round flatbread that can be split into a pocket or toasted alongside a bowl.',
    typicalSection: 'Bakery and flatbreads',
    packageGuidance: 'A 6-count package is practical; large pitas hold the most filling.',
    budget: { label: 'Store-brand pita', searchQuery: 'large pita bread 6 count', reason: 'A basic pita works as a pocket, wedge, or toasted base.' },
    bestForDish: { label: 'Fresh whole-wheat pita', searchQuery: 'fresh whole wheat pita bread', reason: 'Fresh pita opens more easily and whole wheat adds a sturdier bite.' },
    storage: 'Seal tightly and freeze extra breads before they dry out.',
    dietaryCheck: 'Plain pita is usually vegetarian; inspect specialty flavors for animal-derived additives.',
  }),
  guide({
    id: 'starter:potato',
    name: 'Potatoes',
    explanation: 'Starchy tubers that roast, mash, or crisp into a filling meal base.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'A 3–5 lb bag suits repeated use; a large meal may use two medium potatoes.',
    budget: { label: 'Russet potato bag', searchQuery: 'russet potatoes 5 lb bag', reason: 'Russets are versatile for roasting, baking, and mashing.' },
    bestForDish: { label: 'Yukon Gold potatoes', searchQuery: 'Yukon Gold potatoes 3 lb', reason: 'Their creamy flesh holds together well in curries and skillet dishes.' },
    storage: 'Keep cool, dark, dry, and ventilated; do not refrigerate raw potatoes.',
    dietaryCheck: 'Fresh potatoes are vegetarian; prepared potato products may contain animal fat or broth.',
  }),
  guide({
    id: 'starter:sweet-potato',
    name: 'Sweet potatoes',
    explanation: 'Sweet orange-fleshed tubers that roast into a dense base for bowls and stuffed meals.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'Buy a 3 lb bag or two similarly sized loose potatoes for even cooking.',
    budget: { label: 'Conventional sweet potatoes', searchQuery: 'sweet potatoes 3 lb bag', reason: 'A bag works for repeated roasting and stores well.' },
    bestForDish: { label: 'Firm, evenly sized sweet potatoes', searchQuery: 'fresh sweet potatoes', reason: 'Similar sizes finish cooking together and portion more predictably.' },
    storage: 'Keep cool, dark, dry, and ventilated.',
    dietaryCheck: 'Fresh sweet potatoes are vegetarian; review prepared toppings and frozen products.',
  }),
  guide({
    id: 'starter:mixed-vegetables',
    name: 'Frozen mixed vegetables',
    explanation: 'A ready-cut blend that adds several vegetables to a skillet, curry, or rice dish at once.',
    typicalSection: 'Frozen vegetables',
    packageGuidance: 'A 12–32 oz bag is useful; larger resealable bags are easiest to portion.',
    budget: { label: 'Store-brand mixed vegetables', searchQuery: 'frozen mixed vegetables 16 oz', reason: 'The plain blend reduces chopping and can be measured directly from frozen.' },
    bestForDish: { label: 'Sauce-free stir-fry vegetable blend', searchQuery: 'frozen stir fry vegetables no sauce', reason: 'A sauce-free blend gives better texture and leaves seasoning to the recipe.' },
    storage: 'Keep frozen and press excess air from an opened bag.',
    dietaryCheck: 'Choose an unseasoned blend without butter sauce, meat flavoring, or stock.',
  }),
  guide({
    id: 'starter:broccoli',
    name: 'Frozen broccoli',
    explanation: 'Precut broccoli that can go straight into a roast, stir-fry, pasta, or curry.',
    typicalSection: 'Frozen vegetables',
    packageGuidance: 'A 12–16 oz bag supplies a generous vegetable component for one meal.',
    budget: { label: 'Store-brand broccoli cuts', searchQuery: 'frozen broccoli cuts 16 oz', reason: 'Cuts work well when the vegetable will be mixed into a saucy dish.' },
    bestForDish: { label: 'All-floret frozen broccoli', searchQuery: 'frozen broccoli florets 16 oz', reason: 'Florets roast and sear more evenly than a stem-heavy blend.' },
    storage: 'Keep frozen and reseal the bag tightly.',
    dietaryCheck: 'Choose plain broccoli without cheese sauce or animal seasoning.',
  }),
  guide({
    id: 'starter:spinach',
    name: 'Frozen spinach',
    explanation: 'Cooked spinach preserved frozen for easy curries, pasta sauces, and skillet meals.',
    typicalSection: 'Frozen vegetables',
    packageGuidance: 'A 10–16 oz package works for a spinach-forward meal.',
    budget: { label: 'Store-brand chopped spinach', searchQuery: 'frozen chopped spinach 10 oz', reason: 'The compact block is efficient when the full package goes into one dish.' },
    bestForDish: { label: 'Loose-leaf frozen spinach', searchQuery: 'loose leaf frozen spinach bag', reason: 'A loose bag is easier to portion and cooks without thawing a whole block.' },
    storage: 'Keep frozen; squeeze out thawed excess water when the recipe needs concentration.',
    dietaryCheck: 'Choose plain spinach without cream sauce or meat flavoring.',
  }),
  guide({
    id: 'starter:green-peas',
    name: 'Frozen green peas',
    explanation: 'Sweet shelled peas that add color, starch, and some protein directly from the freezer.',
    typicalSection: 'Frozen vegetables',
    packageGuidance: 'A 12–16 oz resealable bag covers one pea-forward meal or several additions.',
    budget: { label: 'Store-brand frozen peas', searchQuery: 'frozen green peas 16 oz', reason: 'The plain standard pea works in rice, curry, pasta, and mash.' },
    bestForDish: { label: 'Petite frozen peas', searchQuery: 'petite frozen peas', reason: 'Smaller peas warm quickly and stay tender in finished sauces.' },
    storage: 'Keep frozen and reseal the bag after measuring.',
    dietaryCheck: 'Choose plain peas without butter sauce or animal seasoning.',
  }),
  guide({
    id: 'starter:onion',
    name: 'Yellow onions',
    explanation: 'An aromatic vegetable that forms the savory base of curries, sauces, and skillet meals.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'A 3 lb bag is useful for repeated cooking; one medium onion is a common meal amount.',
    budget: { label: 'Yellow onion bag', searchQuery: 'yellow onions 3 lb bag', reason: 'Yellow onions handle both long browning and quick sautéing.' },
    bestForDish: { label: 'Firm loose sweet onion', searchQuery: 'fresh sweet onion', reason: 'A sweet onion is useful when larger pieces remain noticeable in the dish.' },
    storage: 'Keep whole onions cool, dark, dry, and ventilated; refrigerate cut onion.',
    dietaryCheck: 'Fresh onion is vegetarian.',
  }),
  guide({
    id: 'starter:bell-pepper',
    name: 'Bell peppers',
    explanation: 'Crisp sweet peppers that add color and fresh texture to wraps, bowls, and stir-fries.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'A three-pack covers one pepper-heavy meal or several smaller additions.',
    budget: { label: 'Mixed bell pepper value pack', searchQuery: 'mixed bell peppers 3 count', reason: 'A multipack provides several colors without buying each pepper separately.' },
    bestForDish: { label: 'Firm red or orange bell peppers', searchQuery: 'fresh red bell peppers', reason: 'Ripe peppers bring the sweetest flavor when they are prominent.' },
    storage: 'Refrigerate whole peppers dry; seal and refrigerate cut pieces.',
    dietaryCheck: 'Fresh bell peppers are vegetarian.',
  }),
  guide({
    id: 'starter:mushrooms',
    name: 'Mushrooms',
    explanation: 'Edible fungi with savory flavor that brown well in pasta, rice, wraps, and skillets.',
    typicalSection: 'Refrigerated fresh produce',
    packageGuidance: 'An 8–16 oz package makes a useful cooked portion because mushrooms shrink.',
    budget: { label: 'Whole white mushrooms', searchQuery: 'whole white mushrooms 16 oz', reason: 'Whole basic mushrooms store better and can be sliced to the needed thickness.' },
    bestForDish: { label: 'Fresh cremini mushrooms', searchQuery: 'fresh cremini mushrooms 16 oz', reason: 'Cremini mushrooms provide a deeper browned flavor in hearty dishes.' },
    storage: 'Refrigerate in breathable packaging and clean shortly before cooking.',
    dietaryCheck: 'Fresh culinary mushrooms are vegetarian; avoid prepared mushrooms in meat gravy.',
  }),
  guide({
    id: 'starter:garlic',
    name: 'Garlic',
    explanation: 'A pungent aromatic bulb used to build flavor in sauces, beans, curries, and marinades.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'A three-bulb sleeve is practical; one bulb contains several recipe portions.',
    budget: { label: 'Fresh garlic bulbs', searchQuery: 'fresh garlic 3 bulb', reason: 'Whole bulbs store longer and give the cook full control over texture.' },
    bestForDish: { label: 'Firm loose garlic', searchQuery: 'fresh loose garlic bulb', reason: 'A heavy, tight bulb tends to have fresher, juicier cloves.' },
    storage: 'Keep whole bulbs cool, dry, dark, and ventilated; refrigerate peeled cloves.',
    dietaryCheck: 'Fresh garlic is vegetarian; prepared garlic paste may include additional flavoring.',
  }),
  guide({
    id: 'starter:ginger',
    name: 'Fresh ginger',
    explanation: 'A peppery aromatic rhizome grated or minced into curries, sauces, and stir-fries.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'Buy one small hand; freeze extra whole or grated for later meals.',
    budget: { label: 'Loose fresh ginger', searchQuery: 'fresh ginger root', reason: 'Buying loose lets the cook choose only the amount needed.' },
    bestForDish: { label: 'Firm young ginger', searchQuery: 'fresh young ginger root', reason: 'A firm piece is juicy, less fibrous, and easier to grate.' },
    storage: 'Refrigerate dry in a bag or freeze tightly wrapped.',
    dietaryCheck: 'Fresh ginger is vegetarian; prepared pastes need an ingredient review.',
  }),
  guide({
    id: 'starter:tomato',
    name: 'Fresh tomatoes',
    explanation: 'Juicy savory fruit used raw for freshness or cooked into a quick sauce.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'Four to six medium tomatoes cover a tomato-forward single meal.',
    budget: { label: 'Roma tomatoes', searchQuery: 'fresh Roma tomatoes', reason: 'Roma tomatoes have less water and work especially well for cooking.' },
    bestForDish: { label: 'Ripe vine tomatoes', searchQuery: 'ripe tomatoes on the vine', reason: 'Use ripe vine tomatoes when the finished dish keeps them raw or lightly cooked.' },
    storage: 'Keep at room temperature until ripe; refrigerate cut tomatoes.',
    dietaryCheck: 'Fresh tomatoes are vegetarian.',
  }),
  guide({
    id: 'starter:tomato-paste',
    name: 'Tomato paste',
    explanation: 'Tomatoes cooked down into a thick concentrate; it is much stronger than tomato sauce.',
    typicalSection: 'Canned tomatoes and pasta sauce',
    packageGuidance: 'A 6 oz can suits recipes using a large amount; a small tube is easier for spoonfuls.',
    budget: { label: 'Store-brand tomato paste can', searchQuery: 'tomato paste 6 oz can', reason: 'The small can is the straightforward format when most of it goes into the meal.' },
    bestForDish: { label: 'Double-concentrated tomato paste tube', searchQuery: 'double concentrated tomato paste tube', reason: 'A resealable tube reduces waste when the recipe needs only a spoonful.' },
    storage: 'Transfer opened canned paste to a covered container or freeze spoon-size portions.',
    dietaryCheck: 'Choose plain tomato paste without meat flavoring.',
  }),
  guide({
    id: 'starter:tomato-sauce',
    name: 'Crushed tomatoes or tomato sauce',
    explanation: 'A pourable canned tomato base used to build pasta sauces, curries, and bean stews.',
    typicalSection: 'Canned tomatoes and pasta sauce',
    packageGuidance: 'A 28 oz can makes a sauce-forward large meal; a 15 oz can suits a smaller amount.',
    budget: { label: 'Store-brand crushed tomatoes', searchQuery: 'crushed tomatoes 28 oz', reason: 'A plain large can provides texture and lets the recipe supply the seasoning.' },
    bestForDish: { label: 'No-salt-added or fire-roasted tomatoes', searchQuery: 'no salt added fire roasted crushed tomatoes', reason: 'No-salt tomatoes give control, while fire-roasted tomatoes add deeper flavor.' },
    storage: 'Refrigerate unused tomatoes in a nonmetal covered container or freeze them.',
    dietaryCheck: 'Review seasoned sauces for cheese, meat stock, or other animal ingredients.',
  }),
  guide({
    id: 'starter:coconut-milk',
    name: 'Full-fat coconut milk',
    explanation: 'A rich canned coconut liquid that makes curries and sauces creamy and calorie-dense.',
    typicalSection: 'International foods or canned cooking ingredients',
    packageGuidance: 'One 13.5 oz can is a practical amount for a rich single meal.',
    budget: { label: 'Store-brand full-fat coconut milk', searchQuery: 'full fat coconut milk 13.5 oz', reason: 'The standard can provides the richness expected by the recipe.' },
    bestForDish: { label: 'Coconut-and-water-only full-fat milk', searchQuery: 'full fat coconut milk coconut water ingredients', reason: 'A simple formula generally incorporates smoothly into a sauce.' },
    storage: 'Shake before opening; refrigerate unused milk in a covered container or freeze it.',
    dietaryCheck: 'Coconut milk is plant-based; do not substitute sweetened cream of coconut.',
  }),
  guide({
    id: 'starter:salsa',
    name: 'Salsa',
    explanation: 'A tomato-and-chile condiment that can season beans, eggs, wraps, and rice bowls quickly.',
    typicalSection: 'Mexican foods or refrigerated dips',
    packageGuidance: 'A 15–16 oz jar or tub covers several generous meal portions.',
    budget: { label: 'Store-brand medium salsa', searchQuery: 'medium salsa 16 oz', reason: 'A basic jar supplies acid, chile, tomato, and seasoning in one ingredient.' },
    bestForDish: { label: 'Fresh refrigerated salsa', searchQuery: 'fresh refrigerated salsa', reason: 'Fresh salsa gives a brighter topping when it is added after cooking.' },
    storage: 'Refrigerate after opening and use a clean spoon.',
    dietaryCheck: 'Most salsa is vegetarian; inspect specialty versions for broth or seafood seasoning.',
  }),
  guide({
    id: 'starter:hummus',
    name: 'Hummus',
    explanation: 'A creamy chickpea-and-tahini spread used as a sauce, dip, or rich wrap filling.',
    typicalSection: 'Refrigerated dips and deli',
    packageGuidance: 'An 8–10 oz tub provides enough for a sauce-heavy single meal.',
    budget: { label: 'Store-brand classic hummus', searchQuery: 'classic hummus 10 oz', reason: 'Plain hummus works in more recipes than a strongly flavored variety.' },
    bestForDish: { label: 'Fresh plain hummus', searchQuery: 'fresh plain hummus', reason: 'A smooth fresh hummus thins easily into a dressing and tastes balanced as a topping.' },
    storage: 'Keep refrigerated and close the tub promptly.',
    dietaryCheck: 'Classic hummus is vegetarian; inspect toppings and flavored varieties.',
  }),
  guide({
    id: 'starter:peanut-butter',
    name: 'Peanut butter',
    explanation: 'Ground peanuts that add fat, protein, and creamy body to savory sauces.',
    typicalSection: 'Nut butter and spreads',
    packageGuidance: 'A 16 oz jar stores well and supports many meals.',
    budget: { label: 'Natural creamy store-brand peanut butter', searchQuery: 'natural creamy peanut butter 16 oz', reason: 'Creamy peanut butter blends into sauce without additional chopping.' },
    bestForDish: { label: 'Peanuts-and-salt-only creamy peanut butter', searchQuery: 'peanuts salt only creamy peanut butter', reason: 'A simple formula keeps sweetness from changing a savory recipe.' },
    storage: 'Stir natural peanut butter well and follow the label for refrigeration.',
    dietaryCheck: 'Peanut butter is vegetarian; check allergy needs and avoid honey if serving a vegan guest.',
  }),
  guide({
    id: 'starter:olive-oil',
    name: 'Olive oil',
    explanation: 'A liquid cooking fat used for browning, roasting, dressing, and increasing meal energy.',
    typicalSection: 'Cooking oils',
    packageGuidance: 'A 500 mL–1 L bottle balances regular use with freshness.',
    budget: { label: 'Everyday olive oil', searchQuery: 'olive oil 1 liter', reason: 'An all-purpose bottle handles routine sautéing and roasting.' },
    bestForDish: { label: 'Extra-virgin olive oil in a dark bottle', searchQuery: 'extra virgin olive oil dark bottle 500 ml', reason: 'Use the more aromatic oil where it will also be tasted as a finish.' },
    storage: 'Keep tightly closed away from heat, air, and direct light.',
    dietaryCheck: 'Pure olive oil is vegetarian; flavored oils need an ingredient review.',
  }),
  guide({
    id: 'starter:soy-sauce',
    name: 'Soy sauce or tamari',
    explanation: 'A salty fermented seasoning that adds savory depth to tofu, noodles, rice, and vegetables.',
    typicalSection: 'Asian or international sauces',
    packageGuidance: 'A 10–15 oz bottle lasts through many recipes.',
    budget: { label: 'Low-sodium soy sauce', searchQuery: 'low sodium soy sauce 15 oz', reason: 'The lower-sodium format leaves more control when several salty ingredients combine.' },
    bestForDish: { label: 'Naturally brewed tamari', searchQuery: 'naturally brewed tamari 10 oz', reason: 'Tamari provides a rounded savory flavor and can suit gluten-free cooking when certified.' },
    storage: 'Close tightly; refrigerate after opening when directed by the label.',
    dietaryCheck: 'Check flavored sauces for fish, oyster, or meat ingredients; soy sauce contains wheat unless labeled otherwise.',
  }),
  guide({
    id: 'starter:vegetable-broth',
    name: 'Vegetable broth',
    explanation: 'A seasoned vegetable cooking liquid used to loosen sauces and simmer grains, beans, or stews.',
    typicalSection: 'Soup, stock, and broth',
    packageGuidance: 'A 32 oz carton covers one broth-heavy dish or several smaller uses.',
    budget: { label: 'Store-brand vegetable broth', searchQuery: 'vegetable broth 32 oz', reason: 'A plain carton is flexible across cuisines.' },
    bestForDish: { label: 'Low-sodium vegetable broth', searchQuery: 'low sodium vegetable broth 32 oz', reason: 'It lets the recipe build flavor without oversalting the finished meal.' },
    storage: 'Refrigerate after opening and use within the package guidance, or freeze portions.',
    dietaryCheck: 'Confirm the label says vegetable broth and contains no chicken, beef, fish, gelatin, or animal fat.',
  }),
  guide({
    id: 'starter:curry-powder',
    name: 'Curry powder',
    aliases: ['Indian-style curry powder'],
    explanation: 'A warm ground-spice blend that commonly combines turmeric, coriander, cumin, and chile for quick curries and roasted vegetables.',
    typicalSection: 'Spices and seasoning blends',
    packageGuidance: 'A 2–4 oz jar covers many single-serving meals; choose mild or hot to match your heat preference.',
    budget: { label: 'Mild curry powder', searchQuery: 'mild curry powder 3 oz', reason: 'A mild all-purpose blend is easy to layer into curry sauce without overwhelming the dish.' },
    bestForDish: { label: 'Madras-style curry powder', searchQuery: 'Madras curry powder', reason: 'This aromatic style brings a deeper toasted-spice profile to tofu, paneer, and vegetable curries.' },
    storage: 'Keep tightly closed in a cool, dry cabinet away from direct light and stove heat.',
    dietaryCheck: 'Plain spice blends are usually plant-based; review the label for dairy, meat flavoring, or shared-equipment allergy notes.',
  }),
  guide({
    id: 'starter:garam-masala',
    name: 'Garam masala',
    aliases: ['Indian finishing spice'],
    explanation: 'An aromatic Indian spice blend used near the end of cooking to add warmth from spices such as cumin, coriander, cardamom, cinnamon, and cloves.',
    typicalSection: 'Spices or Indian foods',
    packageGuidance: 'A 2–4 oz jar stays useful across many dals, bean dishes, paneer meals, and rice bowls.',
    budget: { label: 'Classic garam masala', searchQuery: 'garam masala 3 oz', reason: 'A standard blend adds the expected warm finish across a broad range of Indian-style meals.' },
    bestForDish: { label: 'Salt-free garam masala', searchQuery: 'salt free garam masala', reason: 'A spice-only blend keeps salt control separate and makes its toasted aromatics easier to adjust.' },
    storage: 'Keep airtight in a cool, dark cabinet and replace it when the aroma becomes faint.',
    dietaryCheck: 'Choose a spice-only blend and inspect premixed cooking pastes for dairy or animal-derived flavoring.',
  }),
  guide({
    id: 'starter:taco-seasoning',
    name: 'Taco seasoning',
    aliases: ['Mexican-style seasoning'],
    explanation: 'A savory blend of chile, cumin, garlic, onion, and oregano that quickly seasons beans, tofu, eggs, and vegetables for tacos or burritos.',
    typicalSection: 'Spices or Mexican foods',
    packageGuidance: 'One 1 oz packet seasons a large skillet; a 2–4 oz jar is easier to measure across several recipes.',
    budget: { label: 'Mild taco seasoning', searchQuery: 'mild taco seasoning packet', reason: 'The mild format gives a familiar chile-and-cumin base while leaving heat easy to add separately.' },
    bestForDish: { label: 'Salt-free taco seasoning', searchQuery: 'salt free taco seasoning', reason: 'A salt-free blend makes it easier to balance recipes that also use salsa, cheese, or canned beans.' },
    storage: 'Seal packets after opening or transfer the blend to an airtight spice jar in a cool cabinet.',
    dietaryCheck: 'Review seasoning packets for meat flavoring, dairy, and shared-equipment allergen statements.',
  }),
  guide({
    id: 'starter:italian-seasoning',
    name: 'Italian seasoning',
    aliases: ['Italian herb blend'],
    explanation: 'A dried herb blend, usually led by oregano and basil, for tomato sauces, pasta, beans, and roasted vegetables.',
    typicalSection: 'Spices and dried herbs',
    packageGuidance: 'A 0.5–1.5 oz jar is enough for many meals because dried herbs are used by the teaspoon.',
    budget: { label: 'Classic Italian seasoning', searchQuery: 'Italian seasoning 1 oz', reason: 'A basic oregano-and-basil blend works across pasta, tomato, and bean dishes.' },
    bestForDish: { label: 'Salt-free Italian herb blend', searchQuery: 'salt free Italian herb blend', reason: 'A herb-only blend adds aroma without competing with the salt already present in sauce or cheese.' },
    storage: 'Keep tightly capped away from heat and light; crush a pinch before use to release its aroma.',
    dietaryCheck: 'Pure dried-herb blends are plant-based; check seasoned mixes for cheese or animal-derived flavoring.',
  }),
  guide({
    id: 'starter:shawarma-seasoning',
    name: 'Shawarma seasoning',
    aliases: ['Shawarma spice blend'],
    explanation: 'A Middle Eastern-style blend of warm spices such as cumin, coriander, paprika, turmeric, cinnamon, and allspice for deeply seasoned roasted fillings.',
    typicalSection: 'Spices or Middle Eastern foods',
    packageGuidance: 'A 2–4 oz jar seasons several tofu, paneer, chickpea, or vegetable meals.',
    budget: { label: 'Classic shawarma spice blend', searchQuery: 'shawarma seasoning 3 oz', reason: 'A balanced premixed blend supplies the full warm-spice profile in one measured ingredient.' },
    bestForDish: { label: 'Salt-free shawarma seasoning', searchQuery: 'salt free shawarma seasoning', reason: 'A salt-free blend lets yogurt, hummus, and other savory ingredients be balanced independently.' },
    storage: 'Keep sealed in a cool, dark cabinet and stir or shake before measuring.',
    dietaryCheck: 'Choose a spice-only blend and review marinade packets for dairy or meat-derived flavoring.',
  }),
  guide({
    id: 'starter:cajun-seasoning',
    name: 'Cajun seasoning',
    aliases: ['Louisiana-style seasoning'],
    explanation: 'A bold blend of paprika, chile, garlic, onion, pepper, and herbs for beans, rice, tofu, and skillet vegetables.',
    typicalSection: 'Spices and seasoning blends',
    packageGuidance: 'A 2–5 oz jar supports several meals; check the heat and salt level before adding the full recipe amount.',
    budget: { label: 'Mild Cajun seasoning', searchQuery: 'mild Cajun seasoning', reason: 'A mild blend provides the expected paprika, garlic, and herb base with adjustable heat.' },
    bestForDish: { label: 'Salt-free Cajun seasoning', searchQuery: 'salt free Cajun seasoning', reason: 'It keeps sodium flexible when the dish also includes canned beans, broth, or cheese.' },
    storage: 'Keep tightly closed in a dry cabinet away from stove steam.',
    dietaryCheck: 'Inspect blends for meat flavoring and verify that seafood-style labeling refers only to suggested use, not an included animal ingredient.',
  }),
  guide({
    id: 'starter:berbere-seasoning',
    name: 'Berbere seasoning',
    aliases: ['Ethiopian berbere spice'],
    explanation: 'A fragrant Ethiopian chile-spice blend that gives lentils, beans, and vegetables warm heat and a complex toasted flavor.',
    typicalSection: 'Spices or international foods',
    packageGuidance: 'A 2–4 oz jar lasts through several stews; start modestly because heat varies by blend.',
    budget: { label: 'Classic berbere spice blend', searchQuery: 'berbere seasoning 3 oz', reason: 'A premixed blend brings the layered chile and warm spices that define a berbere-style dish.' },
    bestForDish: { label: 'Salt-free berbere seasoning', searchQuery: 'salt free berbere seasoning', reason: 'A salt-free version makes it easier to tune both heat and seasoning in lentil stews.' },
    storage: 'Store airtight in a cool, dark place and avoid introducing moisture with a wet spoon.',
    dietaryCheck: 'Select a dry spice blend and review prepared berbere sauces for dairy or animal-derived stock.',
  }),
  guide({
    id: 'starter:ras-el-hanout',
    name: 'Ras el hanout',
    aliases: ['Moroccan spice blend'],
    explanation: 'An aromatic North African spice blend that adds warm, floral, and earthy notes to tagines, chickpeas, lentils, and roasted vegetables.',
    typicalSection: 'Spices or international foods',
    packageGuidance: 'A 2–4 oz jar covers many meals; blends vary, so smell and taste a small pinch before cooking.',
    budget: { label: 'Classic ras el hanout', searchQuery: 'ras el hanout spice blend', reason: 'A balanced blend supplies a convenient foundation for Moroccan-style bean and vegetable dishes.' },
    bestForDish: { label: 'Salt-free ras el hanout', searchQuery: 'salt free ras el hanout', reason: 'A spice-only version preserves control when broth, canned tomatoes, or cheese add their own salt.' },
    storage: 'Keep tightly sealed away from light, heat, and moisture.',
    dietaryCheck: 'Dry spice blends are typically plant-based; inspect mixes for added dairy or animal-derived flavoring.',
  }),
  guide({
    id: 'starter:jerk-seasoning',
    name: 'Jerk seasoning',
    aliases: ['Jamaican-style jerk spice'],
    explanation: 'A lively Caribbean-style blend built around allspice, thyme, chile, garlic, and warm spices for tofu, beans, and roasted vegetables.',
    typicalSection: 'Spices or Caribbean foods',
    packageGuidance: 'A 2–5 oz dry-seasoning jar is easy to measure; choose mild or hot according to your heat tolerance.',
    budget: { label: 'Mild dry jerk seasoning', searchQuery: 'mild dry jerk seasoning', reason: 'A mild dry blend supplies the essential allspice-and-thyme character while leaving heat adjustable.' },
    bestForDish: { label: 'Salt-free jerk spice blend', searchQuery: 'salt free jerk spice blend', reason: 'It seasons tofu and beans without forcing extra sodium into a sauce or grain bowl.' },
    storage: 'Keep dry seasoning sealed in a cool cabinet; refrigerate wet jerk marinades after opening.',
    dietaryCheck: 'Choose a plant-based spice blend and inspect bottled marinades for animal-derived flavoring.',
  }),
  guide({
    id: 'starter:smoked-paprika',
    name: 'Smoked paprika',
    aliases: ['Pimenton', 'Spanish smoked paprika'],
    explanation: 'Ground smoked red pepper that contributes deep color and a wood-smoke aroma without requiring meat-based flavoring.',
    typicalSection: 'Spices and seasoning blends',
    packageGuidance: 'A 2–3 oz jar is plenty for many bean, potato, tofu, and tomato-based meals.',
    budget: { label: 'Smoked paprika', searchQuery: 'smoked paprika 2 oz', reason: 'A standard jar adds dependable smoky depth to vegetarian meals.' },
    bestForDish: { label: 'Spanish smoked paprika', searchQuery: 'Spanish smoked paprika pimenton', reason: 'Spanish-style pimenton provides a particularly pronounced smoke aroma for beans and roasted vegetables.' },
    storage: 'Keep tightly closed away from light and heat so its color and smoke aroma last longer.',
    dietaryCheck: 'Pure smoked paprika is plant-based; avoid smoke-flavored seasoning blends that include meat flavoring.',
  }),
  guide({
    id: 'starter:hot-sauce',
    name: 'Hot sauce',
    aliases: ['Chile pepper sauce', 'Buffalo-style hot sauce'],
    explanation: 'A pourable chile-and-vinegar condiment that adds heat, acidity, and concentrated flavor to cooked meals and finishing sauces.',
    typicalSection: 'Condiments and hot sauces',
    packageGuidance: 'A 5–12 oz bottle supports many recipes; compare heat level and sodium before choosing.',
    budget: { label: 'Original cayenne pepper sauce', searchQuery: 'original cayenne pepper hot sauce 5 oz', reason: 'A straightforward chile-and-vinegar sauce works for Buffalo-style tofu, beans, eggs, and bowls.' },
    bestForDish: { label: 'Simple-ingredient cayenne hot sauce', searchQuery: 'cayenne hot sauce peppers vinegar salt', reason: 'A short ingredient list gives predictable heat and acidity without changing the dish with extra sweetness.' },
    storage: 'Close the bottle after use and refrigerate after opening when the label directs.',
    dietaryCheck: 'Most pepper sauces are plant-based; inspect creamy Buffalo sauces for dairy and specialty sauces for fish ingredients.',
  }),
  guide({
    id: 'starter:lemon',
    name: 'Fresh lemon',
    aliases: ['Lemon juice', 'Lemon wedge'],
    explanation: 'A fresh citrus fruit used for juice and zest to brighten rich sauces, beans, grains, and roasted vegetables.',
    typicalSection: 'Fresh produce',
    packageGuidance: 'One medium lemon yields roughly 2–3 tablespoons of juice plus zest; buy whole fruit when both are useful.',
    budget: { label: 'Single fresh lemon', searchQuery: 'fresh lemon each', reason: 'One whole fruit provides both juice and aromatic zest without committing to a larger package.' },
    bestForDish: { label: 'Heavy, smooth-skinned lemon', searchQuery: 'fresh lemons bag', reason: 'A firm lemon that feels heavy for its size is a practical choice when the dish needs plenty of juice.' },
    storage: 'Keep briefly at room temperature or refrigerate in a closed produce bag for longer storage; refrigerate cut fruit.',
    dietaryCheck: 'Fresh lemon is plant-based; bottled lemon preparations may include preservatives but should not need animal ingredients.',
  }),
]);

const guidesByProductId = new Map(GROCERY_GUIDES.map((entry) => [entry.id, entry]));

export function groceryGuideForProductId(id: string): GroceryGuide | undefined {
  return guidesByProductId.get(id);
}

export function retailerLinks(query: string): RetailerLinks {
  const normalized = query.trim();
  const encoded = encodeURIComponent(normalized);
  return Object.freeze({
    heb: `https://www.heb.com/search/?q=${encoded}`,
    instacart: `https://www.instacart.com/store/s?k=${encoded}`,
    walmart: `https://www.walmart.com/search?q=${encoded}`,
  });
}
